# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "todo"
version = "1.8.0"
edition = "2021"
publish = false
license = "MIT"


[dependencies]
image = "0.25.2"
slint = "1.7.2"

[build-dependencies]
slint-build = "1.7.0"
