name: Take Screenshot
on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    - name: Cache cargo build
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-foo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cd slint && cargo build --release --features selfie

    
    - name: Run and take screenshot
      run: |
        cd slint
        cargo run --release --features selfie > cargo.log 2>&1 &
        sleep 5
    

    - name: Upload screenshots as artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: |
          slint/fullscreen1.png
