name: Take Screenshot
on:
    workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Hide Dock
      run: defaults write com.apple.dock autohide -bool true && killall Dock

    - name: Run and take screenshot
      run: |
        screencapture fullscreen1.png

    - name: Install screenresolution
      run: |
        brew install jakehilborn/jakehilborn/displayplacer

    - name: List screen resolutions
      run: |
       displayplacer list
       displayplacer "degree:90"

    - name: Take screenshot
      run: screencapture fullscreen2.png

    - name: Commit and push screenshot
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add fullscreen1.png
        git add fullscreen2.png
        git commit -m "Add updated screenshot"
        git push

    - name: Upload screenshots as artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: |
          fullscreen1.png
          fullscreen2.png
