name: Validate XML
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxml2-utils
      - name: Lint XML files
        run: |
          sudo apt install libxml2-utils --yes
          xmllint --noent --noout $(find . -name '*.xml')
